version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5
        env:
          - RAILS_ENV=test
      - image: circleci/mysql:5.7
        env:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_ROOT_HOST=%

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run:
          name: Load CSV data into MySQL tables(users & posts)
          command: |
            mysql -u root --local-infile -e "LOAD DATA LOCAL INFILE './db/user_seed.csv' INTO TABLE rdm_development.users FIELDS TERMINATED BY ',' (email, name, point, created_at, updated_at)"
            mysql -u root --local-infile -e "LOAD DATA LOCAL INFILE './db/post_seed.csv' INTO TABLE rdm_development.posts FIELDS TERMINATED BY ',' (user_id, title, content, like_count, created_at, updated_at)"

      # run tests!
      - run:
          name: run tests
          command: |
            echo "TODO: add scripts"
